language: node_js
node_js:
  - "node"
warnings_are_errors: false
script:
  - echo "Building react app"
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN

