version: "3.6"

services:
  api:
    build: ./docker/api
    ports:
      - "8080:80"
    volumes:
      - ./:/siteroot
    restart: always
  api-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logbook
      POSTGRES_USER: logbook
    volumes:
      - "apidbdata:/var/lib/postgresql"
  client:
    build: ./docker/client
    ports:
      - "80:3000"
    volumes:
      - ./client:/siteroot
    restart: always
